// --------------------------------------------------------------------------------
// UI HANDLERS SECTION
// --------------------------------------------------------------------------------

function ty(t,e){var i;return i=void 0!==t.getElementsByTagName?t.getElementsByTagName(e||"*"):void 0!==t.querySelectorAll?t.querySelectorAll(e||"*"):[],void 0===e||e&&A(t,e)?T.merge([t],i):i}

function t8(t,e,i,s,r){for(var n,a,o,l,h,d,u=e.createDocumentFragment(),p=[],c=0,f=t.length;c<f;c++)if((n=t[c])||0===n){if("object"===b(n))T.merge(p,n.nodeType?[n]:n);else if(tb.test(n)){for(a=a||u.appendChild(e.createElement("div")),l=t_[o=(t$.exec(n)||["",""])[1].toLowerCase()]||t_._default,a.innerHTML=l[1]+T.htmlPrefilter(n)+l[2],d=l[0];d--;)a=a.lastChild;T.merge(p,a.childNodes),(a=u.firstChild).textContent=""}else p.push(e.createTextNode(n))}for(u.textContent="",c=0;n=p[c++];)if(s&&T.inArray(n,s)>-1)r&&r.push(n);else if(h=to(n),a=ty(u.appendChild(n),"script"),h&&tx(a),i)for(d=0;n=a[d++];)tv.test(n.type||"")&&i.push(n);return u}

function createTag(t){return document.createElement(t)}

function createNS(t){return document.createElementNS(svgNS,t)}

function r(t,e){var i=createTag("span");i.setAttribute("aria-hidden",!0),i.style.fontFamily=e;var s=createTag("span");s.innerText="giItT1WQy@!-/#",i.style.position="absolute",i.style.left="-10000px",i.style.top="-10000px",i.style.fontSize="300px",i.style.fontVariant="normal",i.style.fontStyle="normal",i.style.fontWeight="normal",i.style.letterSpacing="0",i.appendChild(s),document.body.appendChild(i);var r=s.offsetWidth;return s.style.fontFamily=function(t){var e,i=t.split(","),s=i.length,r=[];for(e=0;e<s;e+=1)"sans-serif"!==i[e]&&"monospace"!==i[e]&&r.push(i[e]);return r.join(",")}(t)+", "+e,{node:s,w:r,parent:i}}

function n(t,e){var i,s=document.body&&e?"svg":"canvas",r=getFontProperties(t);if("svg"===s){var n=createNS("text");n.style.fontSize="100px",n.setAttribute("font-family",t.fFamily),n.setAttribute("font-style",r.style),n.setAttribute("font-weight",r.weight),n.textContent="1",t.fClass?(n.style.fontFamily="inherit",n.setAttribute("class",t.fClass)):n.style.fontFamily=t.fFamily,e.appendChild(n),i=n}else{var a=new OffscreenCanvas(500,500).getC

function MaskElement(t,e,i){this.data=t,this.element=e,this.globalData=i,this.storedData=[],this.masksProperties=this.data.masksProperties||[],this.maskElement=null;var s,r,n,a=this.globalData.defs,o=this.masksProperties?this.masksProperties.length:0;this.viewData=createSizedArray(o),this.solidPath="";var l,h,d,u,p,c,f=this.masksProperties,m=0,g=[],$=createElementID(),v="clipPath",_="clip-path";for(r=0;r<o;r+=1)if(("a"!==f[r].mode&&"n"!==f[r].mode||f[r].inv||100!==f[r].o.k||f[r].o.x)&&(v="mask",_="mask"),"s"!==f[r].mode&&"i"!==f[r].mode||0!==m?d=null:((d=createNS("rect")).setAttribute("fill","#ffffff"),d.setAttribute("width",this.element.comp.data.w||0),d.setAttribute("height",this.element.comp.data.h||0),g.push(d)),n=createNS("path"),"n"===f[r].mode)this.viewData[r]={op:PropertyFactory.getProp(this.element,f[r].o,0,.01,this.element),prop:ShapePropertyFactory.getShapeProp(this.element,f[r],3),elem:n,lastPath:""},a.appendChild(n);else{if(m+=1,n.setAttribute("fill","s"===f[r].mode?"#000000":"#ffffff"),n.setAttribute("clip-rule","nonzero"),0!==f[r].x.k?(v="mask",_="mask",c=PropertyFactory.getProp(this.element,f[r].x,0,null,this.element),s=createElementID(),(u=createNS("filter")).setAttribute("id",s),(p=createNS("feMorphology")).setAttribute("operator","erode"),p.setAttribute("in","SourceGraphic"),p.setAttribute("radius","0"),u.appendChild(p),a.appendChild(u),n.setAttribute("stroke","s"===f[r].mode?"#000000":"#ffffff")):(p=null,c=null),this.storedData[r]={elem:n,x:c,expan:p,lastPath:"",lastOperator:"",filterId:s,lastRadius:0},"i"===f[r].mode){h=g.length;var y=createNS("g");for(l=0;l<h;l+=1)y.appendChild(g[l]);var x=createNS("mask");x.setAttribute("mask-type","alpha"),x.setAttribute("id",$+"_"+m),x.appendChild(n),a.appendChild(x),y.setAttribute("mask","url("+getLocationHref()+"#"+$+"_"+m+")"),g.length=0,g.push(y)}else g.push(n);f[r].inv&&!this.solidPath&&(this.solidPath=this.createLayerSolidPath()),this.viewData[r]={elem:n,lastPath:"",op:PropertyFactory.getProp(this.element,f[r].o,0,.01,this.element),prop:ShapePropertyFactory.getShapeProp(this.element,f[r],3),invRect:d},this.viewData[r].prop.k||this.drawPath(f[r],this.viewData[r].prop.v,this.viewData[r])}for(this.maskElement=createNS(v),o=g.length,r=0;r<o;r+=1)this.maskElement.appendChild(g[r]);m>0&&(this.maskElement.setAttribute("id",$),this.element.maskedElement.setAttribute(_,"url("+getLocationHref()+"#"+$+")"),a.appendChild(this.maskElement)),this.viewData.length&&this.element.addRenderableComponent(this)}

function SVGEffects(t){var e,i,s="SourceGraphic",r=t.data.ef?t.data.ef.length:0,n=createElementID(),a=filtersFactory.createFilter(n,!0),o=0;for(this.filters=[],e=0;e<r;e+=1){i=null;var l=t.data.ef[e].ty;registeredEffects[l]&&(i=new registeredEffects[l].effect(a,t.effectsManager.effectElements[e],t,idPrefix+o,s),s=idPrefix+o,registeredEffects[l].countsAsEffect&&(o+=1)),i&&this.filters.push(i)}o&&(t.globalData.defs.appendChild(a),t.layerElement.setAttribute("filter","url("+getLocationHref()+"#"+n+")")),this.filters.length&&t.addRenderableComponent(this)}

function r(){var r,n,a;e||(r=createNS("svg"),n=createNS("filter"),a=createNS("feColorMatrix"),n.setAttribute("id",t),a.setAttribute("type","matrix"),a.setAttribute("color-interpolation-filters","sRGB"),a.setAttribute("values","0.3, 0.3, 0.3, 0, 0, 0.3, 0.3, 0.3, 0, 0, 0.3, 0.3, 0.3, 0, 0, 0.3, 0.3, 0.3, 0, 0"),n.appendChild(a),r.appendChild(n),r.setAttribute("id",t+"_svg"),featureSupport.svgLumaHidden&&(r.style.display="none"),s=r,document.body.appendChild(s),(i=(e=createTag("canvas")).getC

function SVGTintFilter(t,e,i,s,r){this.filterManager=e;var n=createNS("feColorMatrix");n.setAttribute("type","matrix"),n.setAttribute("color-interpolation-filters","linearRGB"),n.setAttribute("values",linearFilterValue+" 1 0"),this.linearFilter=n,n.setAttribute("result",s+"_tint_1"),t.appendChild(n),(n=createNS("feColorMatrix")).setAttribute("type","matrix"),n.setAttribute("color-interpolation-filters","sRGB"),n.setAttribute("values","1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0"),n.setAttribute("result",s+"_tint_2"),t.appendChild(n),this.matrixFilter=n;var a=this.createMergeNode(s,[r,s+"_tint_1",s+"_tint_2"]);t.appendChild(a)}

function SVGFillFilter(t,e,i,s){this.filterManager=e;var r=createNS("feColorMatrix");r.setAttribute("type","matrix"),r.setAttribute("color-interpolation-filters","sRGB"),r.setAttribute("values","1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0"),r.setAttribute("result",s),t.appendChild(r),this.matrixFilter=r}

function SVGTritoneFilter(t,e,i,s){this.filterManager=e;var r=createNS("feColorMatrix");r.setAttribute("type","matrix"),r.setAttribute("color-interpolation-filters","linearRGB"),r.setAttribute("values","0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0"),t.appendChild(r);var n=createNS("feComponentTransfer");n.setAttribute("color-interpolation-filters","sRGB"),n.setAttribute("result",s),this.matrixFilter=n;var a=createNS("feFuncR");a.setAttribute("type","table"),n.appendChild(a),this.feFuncR=a;var o=createNS("feFuncG");o.setAttribute("type","table"),n.appendChild(o),this.feFuncG=o;var l=createNS("feFuncB");l.setAttribute("type","table"),n.appendChild(l),this.feFuncB=l,t.appendChild(n)}

function SVGProLevelsFilter(t,e,i,s){this.filterManager=e;var r=this.filterManager.effectElements,n=createNS("feComponentTransfer");(r[10].p.k||0!==r[10].p.v||r[11].p.k||1!==r[11].p.v||r[12].p.k||1!==r[12].p.v||r[13].p.k||0!==r[13].p.v||r[14].p.k||1!==r[14].p.v)&&(this.feFuncR=this.createFeFunc("feFuncR",n)),(r[17].p.k||0!==r[17].p.v||r[18].p.k||1!==r[18].p.v||r[19].p.k||1!==r[19].p.v||r[20].p.k||0!==r[20].p.v||r[21].p.k||1!==r[21].p.v)&&(this.feFuncG=this.createFeFunc("feFuncG",n)),(r[24].p.k||0!==r[24].p.v||r[25].p.k||1!==r[25].p.v||r[26].p.k||1!==r[26].p.v||r[27].p.k||0!==r[27].p.v||r[28].p.k||1!==r[28].p.v)&&(this.feFuncB=this.createFeFunc("feFuncB",n)),(r[31].p.k||0!==r[31].p.v||r[32].p.k||1!==r[32].p.v||r[33].p.k||1!==r[33].p.v||r[34].p.k||0!==r[34].p.v||r[35].p.k||1!==r[35].p.v)&&(this.feFuncA=this.createFeFunc("feFuncA",n)),(this.feFuncR||this.feFuncG||this.feFuncB||this.feFuncA)&&(n.setAttribute("color-interpolation-filters","sRGB"),t.appendChild(n)),(r[3].p.k||0!==r[3].p.v||r[4].p.k||1!==r[4].p.v||r[5].p.k||1!==r[5].p.v||r[6].p.k||0!==r[6].p.v||r[7].p.k||1!==r[7].p.v)&&((n=createNS("feComponentTransfer")).setAttribute("color-interpolation-filters","sRGB"),n.setAttribute("result",s),t.appendChild(n),this.feFuncRComposed=this.createFeFunc("feFuncR",n),this.feFuncGComposed=this.createFeFunc("feFuncG",n),this.feFuncBComposed=this.createFeFunc("feFuncB",n))}

function SVGDropShadowEffect(t,e,i,s,r){var n=e.container.globalData.renderConfig.filterSize,a=e.data.fs||n;t.setAttribute("x",a.x||n.x),t.setAttribute("y",a.y||n.y),t.setAttribute("width",a.width||n.width),t.setAttribute("height",a.height||n.height),this.filterManager=e;var o=createNS("feGaussianBlur");o.setAttribute("in","SourceAlpha"),o.setAttribute("result",s+"_drop_shadow_1"),o.setAttribute("stdDeviation","0"),this.feGaussianBlur=o,t.appendChild(o);var l=createNS("feOffset");l.setAttribute("dx","25"),l.setAttribute("dy","0"),l.setAttribute("in",s+"_drop_shadow_1"),l.setAttribute("result",s+"_drop_shadow_2"),this.feOffset=l,t.appendChild(l);var h=createNS("feFlood");h.setAttribute("flood-color","#00ff00"),h.setAttribute("flood-opacity","1"),h.setAttribute("result",s+"_drop_shadow_3"),this.feFlood=h,t.appendChild(h);var d=createNS("feComposite");d.setAttribute("in",s+"_drop_shadow_3"),d.setAttribute("in2",s+"_drop_shadow_2"),d.setAttribute("operator","in"),d.setAttribute("result",s+"_drop_shadow_4"),t.appendChild(d);var u=this.createMergeNode(s,[s+"_drop_shadow_4",r]);t.appendChild(u)}

function SVGGaussianBlurEffect(t,e,i,s){t.setAttribute("x","-100%"),t.setAttribute("y","-100%"),t.setAttribute("width","300%"),t.setAttribute("height","300%"),this.filterManager=e;var r=createNS("feGaussianBlur");r.setAttribute("result",s),t.appendChild(r),this.feGaussianBlur=r}

function K(t,e,i,s){let r=a();return t.params.createElements&&Object.keys(s).forEach(n=>{if(!i[n]&&!0===i.auto){let a=t.$el.children(`.${s[n]}`)[0];a||((a=r.createElement("div")).className=s[n],t.$el.append(a)),i[n]=a,e[n]=a}}),i}

